name: Lint

on:
  push:
    branches:
      - rxdb-gh-actions

env:
  CI: true

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create a package.json file for adding the RxDB access token
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: '../'
          file: 'package.json'
          content: |
            {"accessTokens":{"rxdb-premium":"${{ secrets.RXDB_PREMIUM_ACCESS_TOKEN }}"}}

      - name: Install npm dependencies
        run: yarn

      - name: Lint
        run: yarn lint
