name: Test

on:
  push:
    branches:
      - rxdb-gh-actions

env:
  CI: true
  rxdbAccessToken: ${{ secrets.RXDBACCESSTOKEN }}

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create package.json for adding RxDB access token
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: '../'
          file: 'package.json'
          content: |
            { "accessTokens": { "rxdb-premium": "${{ env.rxdbAccessToken }}" } }

      - name: Install npm dependencies
        run: yarn

      - name: Test
        run: yarn test
